### PR TITLE
[2.x] Strip dark classes from welcome component when dark mode isn't selected.

### LINKED ISSUE #1223: Welcome Component Is darkmode support without providing --dark on install
- Jetstream Version: ^2.15
- Jetstream Stack: Inertia & Livewire
- Uses Teams: yes & no
- Laravel Version: ^9.19
- PHP Version: 8.2
- Database Driver & Version: Mysql

### Description:

image

### Steps To Reproduce:

Fresh install laravel Jetstream without --dark. You can optionally enable Teams and choose either stack.

login and view the Welcome component

### PR DESCRIPTION
**Pull request by jessarcher**
Jetstream has a welcome page and a welcome component. The previous implementation was excluding both when stripping dark classes, but it should only exclude the welcome page so that the welcome component does not end up with dark classes.

Fixes #1223

### CODE REVIEW

File: src/Console/InstallCommand.php [hunk 1]
```diff
@@ -262,7 +262,7 @@ protected function installLivewireStack()
             $this->removeDarkClasses((new Finder)
                 ->in(resource_path('views'))
                 ->name('*.blade.php')
-                ->notName('welcome.blade.php')
+                ->filter(fn ($file) => $file->getPathname() !== resource_path('views/welcome.blade.php'))
```
Comment (jessarcher) [inline src/Console/InstallCommand.php:265]: I couldn't use `notPath` here in the same way as the Inertia stack because the `welcome.blade.php` file we want to exclude is in the root of the directory we're searching, and so anything I passed to `notPath` would also match the `welcome.blade.php` file in the `components` directory.
